n1=int(input('Digite um valor: '))
n2=int(input('Digite outro valor: '))
print('A soma de {} e {} é: {}'.format(n1, n2, n1+n2), end=' >>> ')
print('A multiplicação de {} e {} é: {}'.format(n1, n2, n1*n2), end=' >>> ')
print('A divisão de {} e {} é: {:.2f}'.format(n1, n2, n1/n2), end=' >>> ')
print('A divisão inteira de {} e {} é: {}'.format(n1, n2, n1//n2), end=' >>> ')
print('A potência de {} por {} é: {}'.format(n1, n2, n1**n2), end=' >>> ')
print('O resto da divisão entre {} e {} é: {}'.format(n1, n2, n1%n2), end='!')
