algo=input('Digite algo: ')
print('A classe do que foi digitado é: ', type(algo)())
print('Só tem espaços? ', algo.isspace())
print('Ele é alfabético? ', algo.isalpha())
print('Ele é alfanumérico? ', algo.isalnum())
print('Ele é um número? ', algo.isnumeric())
print('Ele é composto apenas de letras minúsculas? ', algo.islower())
print('Ele é composto apenas de letras maiúsculas? ', algo.isupper())
print('Ele é composto por letras maiúsculas e minúsculas? ', algo.istitle())
